#IMPORT .ENV
spring.config.import=optional:file:.env[.properties]
#DATABASE CONNECTION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# ACCESS COOKIE NAME
cineflux.app.access-token.cookie-name=${ACCESS_NAME}
# TOKEN COOKIE NAME
cineflux.app.token.cookie-name=${TOKEN_NAME}
# PUBLIC KEY
app.public-key=classpath:app.pub
# PRIVATE KEY
app.private-key=classpath:app.key
# ACCESS EXPIRATION
access.expiration=${EXPIRATION_ACCESS}
# TOKEN EXPIRATION
token.expiration=${EXPIRATION_TOKEN}