#IMPORT .ENV
spring.config.import=optional:file:.env[.properties]
#DATABASE CONNECTION
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}