#IMPORT .ENV
spring.config.import=optional:file:.env[.properties]
# DATASOURCE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
# H2 CLIENT
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JWT SECRET
cineflux.app.jwtSecret=${JWT_SECRET}
# COOKIE NAME
cineflux.app.jwtCookieName=${COOKIE_NAME}