#IMPORT .ENV
spring.config.import=optional:file:.env[.properties]
# DATASOURCE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
# H2 CLIENT
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# ACCESS COOKIE NAME
cineflux.app.access-token.cookie-name=${ACCESS_NAME}
# TOKEN COOKIE NAME
cineflux.app.token.cookie-name=${TOKEN_NAME}
# PUBLIC KEY
app.public-key=classpath:app.pub
# PRIVATE KEY
app.private-key=classpath:app.key
# ACCESS EXPIRATION
access.expiration=${EXPIRATION_ACCESS}
# TOKEN EXPIRATION
token.expiration=${EXPIRATION_TOKEN}